/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ArbitrationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "APPEAL_JUROR_INCREMENT"
      | "ARBITRATION_FEE"
      | "INITIAL_JUROR_COUNT"
      | "STAKE_AMOUNT"
      | "appealDispute"
      | "arbitrationToken"
      | "commitVote"
      | "createDispute"
      | "disputeCounter"
      | "disputes"
      | "finalizeDispute"
      | "getDisputeResult"
      | "getEvidence"
      | "getEvidenceCount"
      | "getJurorCategories"
      | "getJurorCountByCategory"
      | "getSelectedJurors"
      | "jurors"
      | "jurorsByCategory"
      | "marketplace"
      | "revealVote"
      | "setMarketplace"
      | "stakeAsJuror"
      | "submitEvidence"
      | "unstake"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeAppealed"
      | "DisputeCreated"
      | "DisputeResolved"
      | "EvidenceSubmitted"
      | "JurorSelected"
      | "JurorStaked"
      | "JurorUnstaked"
      | "RewardsDistributed"
      | "VoteCast"
      | "VoteCommitted"
      | "VoteRevealed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "APPEAL_JUROR_INCREMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ARBITRATION_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_JUROR_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STAKE_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "appealDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "arbitrationToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "commitVote",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createDispute",
    values: [BigNumberish, AddressLike, AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDisputeResult",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidence",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidenceCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJurorCategories",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getJurorCountByCategory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSelectedJurors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "jurors", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "jurorsByCategory",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketplace",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealVote",
    values: [BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketplace",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeAsJuror",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEvidence",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "unstake", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "APPEAL_JUROR_INCREMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ARBITRATION_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_JUROR_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STAKE_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "appealDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "arbitrationToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "commitVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDisputeResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidenceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getJurorCategories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getJurorCountByCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSelectedJurors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jurors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "jurorsByCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revealVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMarketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeAsJuror",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
}

export namespace DisputeAppealedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    newJurorCount: BigNumberish
  ];
  export type OutputTuple = [disputeId: bigint, newJurorCount: bigint];
  export interface OutputObject {
    disputeId: bigint;
    newJurorCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeCreatedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    jobId: BigNumberish,
    category: string
  ];
  export type OutputTuple = [
    disputeId: bigint,
    jobId: bigint,
    category: string
  ];
  export interface OutputObject {
    disputeId: bigint;
    jobId: bigint;
    category: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    clientWon: boolean,
    majorityVotes: BigNumberish
  ];
  export type OutputTuple = [
    disputeId: bigint,
    clientWon: boolean,
    majorityVotes: bigint
  ];
  export interface OutputObject {
    disputeId: bigint;
    clientWon: boolean;
    majorityVotes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceSubmittedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    submitter: AddressLike,
    evidenceHash: string
  ];
  export type OutputTuple = [
    disputeId: bigint,
    submitter: string,
    evidenceHash: string
  ];
  export interface OutputObject {
    disputeId: bigint;
    submitter: string;
    evidenceHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurorSelectedEvent {
  export type InputTuple = [disputeId: BigNumberish, juror: AddressLike];
  export type OutputTuple = [disputeId: bigint, juror: string];
  export interface OutputObject {
    disputeId: bigint;
    juror: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurorStakedEvent {
  export type InputTuple = [
    juror: AddressLike,
    amount: BigNumberish,
    categories: string[]
  ];
  export type OutputTuple = [
    juror: string,
    amount: bigint,
    categories: string[]
  ];
  export interface OutputObject {
    juror: string;
    amount: bigint;
    categories: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurorUnstakedEvent {
  export type InputTuple = [juror: AddressLike, amount: BigNumberish];
  export type OutputTuple = [juror: string, amount: bigint];
  export interface OutputObject {
    juror: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsDistributedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    winners: AddressLike[],
    rewardPerJuror: BigNumberish
  ];
  export type OutputTuple = [
    disputeId: bigint,
    winners: string[],
    rewardPerJuror: bigint
  ];
  export interface OutputObject {
    disputeId: bigint;
    winners: string[];
    rewardPerJuror: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    juror: AddressLike,
    votedForClient: boolean
  ];
  export type OutputTuple = [
    disputeId: bigint,
    juror: string,
    votedForClient: boolean
  ];
  export interface OutputObject {
    disputeId: bigint;
    juror: string;
    votedForClient: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCommittedEvent {
  export type InputTuple = [disputeId: BigNumberish, juror: AddressLike];
  export type OutputTuple = [disputeId: bigint, juror: string];
  export interface OutputObject {
    disputeId: bigint;
    juror: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteRevealedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    juror: AddressLike,
    voteForClient: boolean
  ];
  export type OutputTuple = [
    disputeId: bigint,
    juror: string,
    voteForClient: boolean
  ];
  export interface OutputObject {
    disputeId: bigint;
    juror: string;
    voteForClient: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Arbitration extends BaseContract {
  connect(runner?: ContractRunner | null): Arbitration;
  waitForDeployment(): Promise<this>;

  interface: ArbitrationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  APPEAL_JUROR_INCREMENT: TypedContractMethod<[], [bigint], "view">;

  ARBITRATION_FEE: TypedContractMethod<[], [bigint], "view">;

  INITIAL_JUROR_COUNT: TypedContractMethod<[], [bigint], "view">;

  STAKE_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  appealDispute: TypedContractMethod<
    [_disputeId: BigNumberish],
    [void],
    "payable"
  >;

  arbitrationToken: TypedContractMethod<[], [string], "view">;

  commitVote: TypedContractMethod<
    [_disputeId: BigNumberish, _commitHash: BytesLike],
    [void],
    "nonpayable"
  >;

  createDispute: TypedContractMethod<
    [
      _jobId: BigNumberish,
      _client: AddressLike,
      _worker: AddressLike,
      _category: string,
      _amount: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  disputeCounter: TypedContractMethod<[], [bigint], "view">;

  disputes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        disputeId: bigint;
        jobId: bigint;
        client: string;
        worker: string;
        category: string;
        amount: bigint;
        isActive: boolean;
        isResolved: boolean;
        votesForClient: bigint;
        votesForWorker: bigint;
        jurorCount: bigint;
        appealCount: bigint;
        arbitrationFeePaid: bigint;
        createdAt: bigint;
        commitPeriodEnd: bigint;
        revealPeriodEnd: bigint;
      }
    ],
    "view"
  >;

  finalizeDispute: TypedContractMethod<
    [_disputeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getDisputeResult: TypedContractMethod<
    [_disputeId: BigNumberish],
    [[boolean, boolean] & { isResolved: boolean; clientWon: boolean }],
    "view"
  >;

  getEvidence: TypedContractMethod<
    [_disputeId: BigNumberish, _index: BigNumberish],
    [string],
    "view"
  >;

  getEvidenceCount: TypedContractMethod<
    [_disputeId: BigNumberish],
    [bigint],
    "view"
  >;

  getJurorCategories: TypedContractMethod<
    [_juror: AddressLike],
    [string[]],
    "view"
  >;

  getJurorCountByCategory: TypedContractMethod<
    [_category: string],
    [bigint],
    "view"
  >;

  getSelectedJurors: TypedContractMethod<
    [_disputeId: BigNumberish],
    [string[]],
    "view"
  >;

  jurors: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint] & {
        isStaked: boolean;
        stakedAmount: bigint;
        casesVoted: bigint;
        correctVotes: bigint;
      }
    ],
    "view"
  >;

  jurorsByCategory: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [string],
    "view"
  >;

  marketplace: TypedContractMethod<[], [string], "view">;

  revealVote: TypedContractMethod<
    [_disputeId: BigNumberish, _voteForClient: boolean, _salt: string],
    [void],
    "nonpayable"
  >;

  setMarketplace: TypedContractMethod<
    [_marketplace: AddressLike],
    [void],
    "nonpayable"
  >;

  stakeAsJuror: TypedContractMethod<
    [_categories: string[]],
    [void],
    "nonpayable"
  >;

  submitEvidence: TypedContractMethod<
    [_disputeId: BigNumberish, _evidenceHash: string],
    [void],
    "nonpayable"
  >;

  unstake: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "APPEAL_JUROR_INCREMENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ARBITRATION_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_JUROR_COUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STAKE_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "appealDispute"
  ): TypedContractMethod<[_disputeId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "arbitrationToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "commitVote"
  ): TypedContractMethod<
    [_disputeId: BigNumberish, _commitHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDispute"
  ): TypedContractMethod<
    [
      _jobId: BigNumberish,
      _client: AddressLike,
      _worker: AddressLike,
      _category: string,
      _amount: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "disputeCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "disputes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        disputeId: bigint;
        jobId: bigint;
        client: string;
        worker: string;
        category: string;
        amount: bigint;
        isActive: boolean;
        isResolved: boolean;
        votesForClient: bigint;
        votesForWorker: bigint;
        jurorCount: bigint;
        appealCount: bigint;
        arbitrationFeePaid: bigint;
        createdAt: bigint;
        commitPeriodEnd: bigint;
        revealPeriodEnd: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "finalizeDispute"
  ): TypedContractMethod<[_disputeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDisputeResult"
  ): TypedContractMethod<
    [_disputeId: BigNumberish],
    [[boolean, boolean] & { isResolved: boolean; clientWon: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvidence"
  ): TypedContractMethod<
    [_disputeId: BigNumberish, _index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvidenceCount"
  ): TypedContractMethod<[_disputeId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getJurorCategories"
  ): TypedContractMethod<[_juror: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getJurorCountByCategory"
  ): TypedContractMethod<[_category: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSelectedJurors"
  ): TypedContractMethod<[_disputeId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "jurors"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint] & {
        isStaked: boolean;
        stakedAmount: bigint;
        casesVoted: bigint;
        correctVotes: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "jurorsByCategory"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "marketplace"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revealVote"
  ): TypedContractMethod<
    [_disputeId: BigNumberish, _voteForClient: boolean, _salt: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMarketplace"
  ): TypedContractMethod<[_marketplace: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeAsJuror"
  ): TypedContractMethod<[_categories: string[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitEvidence"
  ): TypedContractMethod<
    [_disputeId: BigNumberish, _evidenceHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "DisputeAppealed"
  ): TypedContractEvent<
    DisputeAppealedEvent.InputTuple,
    DisputeAppealedEvent.OutputTuple,
    DisputeAppealedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeCreated"
  ): TypedContractEvent<
    DisputeCreatedEvent.InputTuple,
    DisputeCreatedEvent.OutputTuple,
    DisputeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceSubmitted"
  ): TypedContractEvent<
    EvidenceSubmittedEvent.InputTuple,
    EvidenceSubmittedEvent.OutputTuple,
    EvidenceSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "JurorSelected"
  ): TypedContractEvent<
    JurorSelectedEvent.InputTuple,
    JurorSelectedEvent.OutputTuple,
    JurorSelectedEvent.OutputObject
  >;
  getEvent(
    key: "JurorStaked"
  ): TypedContractEvent<
    JurorStakedEvent.InputTuple,
    JurorStakedEvent.OutputTuple,
    JurorStakedEvent.OutputObject
  >;
  getEvent(
    key: "JurorUnstaked"
  ): TypedContractEvent<
    JurorUnstakedEvent.InputTuple,
    JurorUnstakedEvent.OutputTuple,
    JurorUnstakedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsDistributed"
  ): TypedContractEvent<
    RewardsDistributedEvent.InputTuple,
    RewardsDistributedEvent.OutputTuple,
    RewardsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;
  getEvent(
    key: "VoteCommitted"
  ): TypedContractEvent<
    VoteCommittedEvent.InputTuple,
    VoteCommittedEvent.OutputTuple,
    VoteCommittedEvent.OutputObject
  >;
  getEvent(
    key: "VoteRevealed"
  ): TypedContractEvent<
    VoteRevealedEvent.InputTuple,
    VoteRevealedEvent.OutputTuple,
    VoteRevealedEvent.OutputObject
  >;

  filters: {
    "DisputeAppealed(uint256,uint256)": TypedContractEvent<
      DisputeAppealedEvent.InputTuple,
      DisputeAppealedEvent.OutputTuple,
      DisputeAppealedEvent.OutputObject
    >;
    DisputeAppealed: TypedContractEvent<
      DisputeAppealedEvent.InputTuple,
      DisputeAppealedEvent.OutputTuple,
      DisputeAppealedEvent.OutputObject
    >;

    "DisputeCreated(uint256,uint256,string)": TypedContractEvent<
      DisputeCreatedEvent.InputTuple,
      DisputeCreatedEvent.OutputTuple,
      DisputeCreatedEvent.OutputObject
    >;
    DisputeCreated: TypedContractEvent<
      DisputeCreatedEvent.InputTuple,
      DisputeCreatedEvent.OutputTuple,
      DisputeCreatedEvent.OutputObject
    >;

    "DisputeResolved(uint256,bool,uint256)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "EvidenceSubmitted(uint256,address,string)": TypedContractEvent<
      EvidenceSubmittedEvent.InputTuple,
      EvidenceSubmittedEvent.OutputTuple,
      EvidenceSubmittedEvent.OutputObject
    >;
    EvidenceSubmitted: TypedContractEvent<
      EvidenceSubmittedEvent.InputTuple,
      EvidenceSubmittedEvent.OutputTuple,
      EvidenceSubmittedEvent.OutputObject
    >;

    "JurorSelected(uint256,address)": TypedContractEvent<
      JurorSelectedEvent.InputTuple,
      JurorSelectedEvent.OutputTuple,
      JurorSelectedEvent.OutputObject
    >;
    JurorSelected: TypedContractEvent<
      JurorSelectedEvent.InputTuple,
      JurorSelectedEvent.OutputTuple,
      JurorSelectedEvent.OutputObject
    >;

    "JurorStaked(address,uint256,string[])": TypedContractEvent<
      JurorStakedEvent.InputTuple,
      JurorStakedEvent.OutputTuple,
      JurorStakedEvent.OutputObject
    >;
    JurorStaked: TypedContractEvent<
      JurorStakedEvent.InputTuple,
      JurorStakedEvent.OutputTuple,
      JurorStakedEvent.OutputObject
    >;

    "JurorUnstaked(address,uint256)": TypedContractEvent<
      JurorUnstakedEvent.InputTuple,
      JurorUnstakedEvent.OutputTuple,
      JurorUnstakedEvent.OutputObject
    >;
    JurorUnstaked: TypedContractEvent<
      JurorUnstakedEvent.InputTuple,
      JurorUnstakedEvent.OutputTuple,
      JurorUnstakedEvent.OutputObject
    >;

    "RewardsDistributed(uint256,address[],uint256)": TypedContractEvent<
      RewardsDistributedEvent.InputTuple,
      RewardsDistributedEvent.OutputTuple,
      RewardsDistributedEvent.OutputObject
    >;
    RewardsDistributed: TypedContractEvent<
      RewardsDistributedEvent.InputTuple,
      RewardsDistributedEvent.OutputTuple,
      RewardsDistributedEvent.OutputObject
    >;

    "VoteCast(uint256,address,bool)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;

    "VoteCommitted(uint256,address)": TypedContractEvent<
      VoteCommittedEvent.InputTuple,
      VoteCommittedEvent.OutputTuple,
      VoteCommittedEvent.OutputObject
    >;
    VoteCommitted: TypedContractEvent<
      VoteCommittedEvent.InputTuple,
      VoteCommittedEvent.OutputTuple,
      VoteCommittedEvent.OutputObject
    >;

    "VoteRevealed(uint256,address,bool)": TypedContractEvent<
      VoteRevealedEvent.InputTuple,
      VoteRevealedEvent.OutputTuple,
      VoteRevealedEvent.OutputObject
    >;
    VoteRevealed: TypedContractEvent<
      VoteRevealedEvent.InputTuple,
      VoteRevealedEvent.OutputTuple,
      VoteRevealedEvent.OutputObject
    >;
  };
}
