/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface JobEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "USDC_ADDRESS"
      | "client"
      | "fundFromMarketplace"
      | "isDisputed"
      | "lockedAmount"
      | "marketplace"
      | "payWorker"
      | "raiseDispute"
      | "refundClient"
      | "releaseFullPayment"
      | "releasedAmount"
      | "setWorker"
      | "totalBudget"
      | "usdc"
      | "worker"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeRaised"
      | "FullPaymentReleased"
      | "Funded"
      | "RefundIssued"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "USDC_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "client", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fundFromMarketplace",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isDisputed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockedAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketplace",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "payWorker",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refundClient",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseFullPayment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releasedAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setWorker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBudget",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(functionFragment: "worker", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "USDC_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "client", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundFromMarketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isDisputed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payWorker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundClient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseFullPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releasedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setWorker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "worker", data: BytesLike): Result;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FullPaymentReleasedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundIssuedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface JobEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): JobEscrow;
  waitForDeployment(): Promise<this>;

  interface: JobEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  USDC_ADDRESS: TypedContractMethod<[], [string], "view">;

  client: TypedContractMethod<[], [string], "view">;

  fundFromMarketplace: TypedContractMethod<[], [void], "nonpayable">;

  isDisputed: TypedContractMethod<[], [boolean], "view">;

  lockedAmount: TypedContractMethod<[], [bigint], "view">;

  marketplace: TypedContractMethod<[], [string], "view">;

  payWorker: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  raiseDispute: TypedContractMethod<[], [void], "nonpayable">;

  refundClient: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  releaseFullPayment: TypedContractMethod<[], [void], "nonpayable">;

  releasedAmount: TypedContractMethod<[], [bigint], "view">;

  setWorker: TypedContractMethod<[_worker: AddressLike], [void], "nonpayable">;

  totalBudget: TypedContractMethod<[], [bigint], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  worker: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "USDC_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "client"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundFromMarketplace"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isDisputed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lockedAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketplace"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payWorker"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refundClient"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseFullPayment"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releasedAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setWorker"
  ): TypedContractMethod<[_worker: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalBudget"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "worker"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "FullPaymentReleased"
  ): TypedContractEvent<
    FullPaymentReleasedEvent.InputTuple,
    FullPaymentReleasedEvent.OutputTuple,
    FullPaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "Funded"
  ): TypedContractEvent<
    FundedEvent.InputTuple,
    FundedEvent.OutputTuple,
    FundedEvent.OutputObject
  >;
  getEvent(
    key: "RefundIssued"
  ): TypedContractEvent<
    RefundIssuedEvent.InputTuple,
    RefundIssuedEvent.OutputTuple,
    RefundIssuedEvent.OutputObject
  >;

  filters: {
    "DisputeRaised()": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "FullPaymentReleased(uint256)": TypedContractEvent<
      FullPaymentReleasedEvent.InputTuple,
      FullPaymentReleasedEvent.OutputTuple,
      FullPaymentReleasedEvent.OutputObject
    >;
    FullPaymentReleased: TypedContractEvent<
      FullPaymentReleasedEvent.InputTuple,
      FullPaymentReleasedEvent.OutputTuple,
      FullPaymentReleasedEvent.OutputObject
    >;

    "Funded(uint256)": TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;
    Funded: TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;

    "RefundIssued(uint256)": TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
    RefundIssued: TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
  };
}
