/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace JobMarketplace {
  export type ApplicationStruct = {
    worker: AddressLike;
    coverLetterHash: string;
    workHistoryHash: string;
    timestamp: BigNumberish;
  };

  export type ApplicationStructOutput = [
    worker: string,
    coverLetterHash: string,
    workHistoryHash: string,
    timestamp: bigint
  ] & {
    worker: string;
    coverLetterHash: string;
    workHistoryHash: string;
    timestamp: bigint;
  };

  export type JobStruct = {
    jobId: BigNumberish;
    client: AddressLike;
    title: string;
    description: string;
    skills: string;
    categoryId: BigNumberish;
    budget: BigNumberish;
    isActive: boolean;
    isCompleted: boolean;
    isFunded: boolean;
    selectedWorker: AddressLike;
    escrowContract: AddressLike;
    workSubmissionHash: string;
    workSubmitted: boolean;
    disputeId: BigNumberish;
    isDisputed: boolean;
    isCancelled: boolean;
  };

  export type JobStructOutput = [
    jobId: bigint,
    client: string,
    title: string,
    description: string,
    skills: string,
    categoryId: bigint,
    budget: bigint,
    isActive: boolean,
    isCompleted: boolean,
    isFunded: boolean,
    selectedWorker: string,
    escrowContract: string,
    workSubmissionHash: string,
    workSubmitted: boolean,
    disputeId: bigint,
    isDisputed: boolean,
    isCancelled: boolean
  ] & {
    jobId: bigint;
    client: string;
    title: string;
    description: string;
    skills: string;
    categoryId: bigint;
    budget: bigint;
    isActive: boolean;
    isCompleted: boolean;
    isFunded: boolean;
    selectedWorker: string;
    escrowContract: string;
    workSubmissionHash: string;
    workSubmitted: boolean;
    disputeId: bigint;
    isDisputed: boolean;
    isCancelled: boolean;
  };
}

export interface JobMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "USDC_ADDRESS"
      | "acceptWorkAndPay"
      | "activeJobIds"
      | "activeJobIndex"
      | "applyToJob"
      | "arbitration"
      | "cancelJob"
      | "clientJobs"
      | "fundJobEscrow"
      | "getActiveJobCount"
      | "getActiveJobs"
      | "getApplications"
      | "getClientJobs"
      | "getJob"
      | "getWorkerApplications"
      | "getWorkerJobs"
      | "hasApplied"
      | "jobApplications"
      | "jobCounter"
      | "jobs"
      | "owner"
      | "postJob"
      | "raiseDispute"
      | "rateClient"
      | "rateWorker"
      | "renounceOwnership"
      | "reputationSystem"
      | "resolveDispute"
      | "selectWorker"
      | "submitWork"
      | "transferOwnership"
      | "usdc"
      | "workerApplications"
      | "workerJobs"
      | "workerRegistry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApplicationSubmitted"
      | "DisputeRaised"
      | "DisputeResolved"
      | "EscrowCreated"
      | "JobCancelled"
      | "JobPosted"
      | "OwnershipTransferred"
      | "PaymentReleased"
      | "WorkSubmitted"
      | "WorkerSelected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "USDC_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptWorkAndPay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activeJobIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activeJobIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "applyToJob",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "arbitration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "clientJobs",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundJobEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveJobCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveJobs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getApplications",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClientJobs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkerApplications",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkerJobs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasApplied",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "jobApplications",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "jobCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postJob",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rateClient",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rateWorker",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputationSystem",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "selectWorker",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitWork",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "workerApplications",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "workerJobs",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "workerRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "USDC_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptWorkAndPay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeJobIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeJobIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "applyToJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "arbitration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "clientJobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundJobEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveJobCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveJobs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApplications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClientJobs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWorkerApplications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkerJobs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasApplied", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "jobApplications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobCounter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rateClient", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rateWorker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationSystem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "selectWorker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitWork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "workerApplications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "workerJobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "workerRegistry",
    data: BytesLike
  ): Result;
}

export namespace ApplicationSubmittedEvent {
  export type InputTuple = [jobId: BigNumberish, worker: AddressLike];
  export type OutputTuple = [jobId: bigint, worker: string];
  export interface OutputObject {
    jobId: bigint;
    worker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [jobId: BigNumberish, disputeId: BigNumberish];
  export type OutputTuple = [jobId: bigint, disputeId: bigint];
  export interface OutputObject {
    jobId: bigint;
    disputeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [jobId: BigNumberish, clientWon: boolean];
  export type OutputTuple = [jobId: bigint, clientWon: boolean];
  export interface OutputObject {
    jobId: bigint;
    clientWon: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [jobId: BigNumberish, escrowContract: AddressLike];
  export type OutputTuple = [jobId: bigint, escrowContract: string];
  export interface OutputObject {
    jobId: bigint;
    escrowContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCancelledEvent {
  export type InputTuple = [jobId: BigNumberish];
  export type OutputTuple = [jobId: bigint];
  export interface OutputObject {
    jobId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobPostedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    client: AddressLike,
    title: string,
    categoryId: BigNumberish,
    budget: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    client: string,
    title: string,
    categoryId: bigint,
    budget: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    client: string;
    title: string;
    categoryId: bigint;
    budget: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReleasedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    worker: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [jobId: bigint, worker: string, amount: bigint];
  export interface OutputObject {
    jobId: bigint;
    worker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkSubmittedEvent {
  export type InputTuple = [jobId: BigNumberish, workHash: string];
  export type OutputTuple = [jobId: bigint, workHash: string];
  export interface OutputObject {
    jobId: bigint;
    workHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkerSelectedEvent {
  export type InputTuple = [jobId: BigNumberish, worker: AddressLike];
  export type OutputTuple = [jobId: bigint, worker: string];
  export interface OutputObject {
    jobId: bigint;
    worker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface JobMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): JobMarketplace;
  waitForDeployment(): Promise<this>;

  interface: JobMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  USDC_ADDRESS: TypedContractMethod<[], [string], "view">;

  acceptWorkAndPay: TypedContractMethod<
    [_jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  activeJobIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  activeJobIndex: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  applyToJob: TypedContractMethod<
    [_jobId: BigNumberish, _coverLetterHash: string, _workHistoryHash: string],
    [void],
    "nonpayable"
  >;

  arbitration: TypedContractMethod<[], [string], "view">;

  cancelJob: TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;

  clientJobs: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  fundJobEscrow: TypedContractMethod<
    [_jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getActiveJobCount: TypedContractMethod<[], [bigint], "view">;

  getActiveJobs: TypedContractMethod<[], [bigint[]], "view">;

  getApplications: TypedContractMethod<
    [_jobId: BigNumberish],
    [JobMarketplace.ApplicationStructOutput[]],
    "view"
  >;

  getClientJobs: TypedContractMethod<
    [_client: AddressLike],
    [bigint[]],
    "view"
  >;

  getJob: TypedContractMethod<
    [_jobId: BigNumberish],
    [JobMarketplace.JobStructOutput],
    "view"
  >;

  getWorkerApplications: TypedContractMethod<
    [_worker: AddressLike],
    [bigint[]],
    "view"
  >;

  getWorkerJobs: TypedContractMethod<
    [_worker: AddressLike],
    [bigint[]],
    "view"
  >;

  hasApplied: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  jobApplications: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, string, bigint] & {
        worker: string;
        coverLetterHash: string;
        workHistoryHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  jobCounter: TypedContractMethod<[], [bigint], "view">;

  jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        string,
        string,
        string,
        boolean,
        bigint,
        boolean,
        boolean
      ] & {
        jobId: bigint;
        client: string;
        title: string;
        description: string;
        skills: string;
        categoryId: bigint;
        budget: bigint;
        isActive: boolean;
        isCompleted: boolean;
        isFunded: boolean;
        selectedWorker: string;
        escrowContract: string;
        workSubmissionHash: string;
        workSubmitted: boolean;
        disputeId: bigint;
        isDisputed: boolean;
        isCancelled: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  postJob: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _skills: string,
      _categoryId: BigNumberish,
      _budget: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  raiseDispute: TypedContractMethod<
    [_jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  rateClient: TypedContractMethod<
    [_jobId: BigNumberish, _rating: BigNumberish],
    [void],
    "nonpayable"
  >;

  rateWorker: TypedContractMethod<
    [_jobId: BigNumberish, _rating: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputationSystem: TypedContractMethod<[], [string], "view">;

  resolveDispute: TypedContractMethod<
    [_jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  selectWorker: TypedContractMethod<
    [_jobId: BigNumberish, _worker: AddressLike],
    [void],
    "nonpayable"
  >;

  submitWork: TypedContractMethod<
    [_jobId: BigNumberish, _workHash: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  workerApplications: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  workerJobs: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  workerRegistry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "USDC_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptWorkAndPay"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "activeJobIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "activeJobIndex"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "applyToJob"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _coverLetterHash: string, _workHistoryHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "arbitration"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelJob"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "clientJobs"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fundJobEscrow"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveJobCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getActiveJobs"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getApplications"
  ): TypedContractMethod<
    [_jobId: BigNumberish],
    [JobMarketplace.ApplicationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClientJobs"
  ): TypedContractMethod<[_client: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [_jobId: BigNumberish],
    [JobMarketplace.JobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWorkerApplications"
  ): TypedContractMethod<[_worker: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getWorkerJobs"
  ): TypedContractMethod<[_worker: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hasApplied"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobApplications"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, string, bigint] & {
        worker: string;
        coverLetterHash: string;
        workHistoryHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        string,
        string,
        string,
        boolean,
        bigint,
        boolean,
        boolean
      ] & {
        jobId: bigint;
        client: string;
        title: string;
        description: string;
        skills: string;
        categoryId: bigint;
        budget: bigint;
        isActive: boolean;
        isCompleted: boolean;
        isFunded: boolean;
        selectedWorker: string;
        escrowContract: string;
        workSubmissionHash: string;
        workSubmitted: boolean;
        disputeId: bigint;
        isDisputed: boolean;
        isCancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "postJob"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _skills: string,
      _categoryId: BigNumberish,
      _budget: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rateClient"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _rating: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rateWorker"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _rating: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputationSystem"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "selectWorker"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _worker: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitWork"
  ): TypedContractMethod<
    [_jobId: BigNumberish, _workHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "workerApplications"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "workerJobs"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "workerRegistry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ApplicationSubmitted"
  ): TypedContractEvent<
    ApplicationSubmittedEvent.InputTuple,
    ApplicationSubmittedEvent.OutputTuple,
    ApplicationSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "JobCancelled"
  ): TypedContractEvent<
    JobCancelledEvent.InputTuple,
    JobCancelledEvent.OutputTuple,
    JobCancelledEvent.OutputObject
  >;
  getEvent(
    key: "JobPosted"
  ): TypedContractEvent<
    JobPostedEvent.InputTuple,
    JobPostedEvent.OutputTuple,
    JobPostedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReleased"
  ): TypedContractEvent<
    PaymentReleasedEvent.InputTuple,
    PaymentReleasedEvent.OutputTuple,
    PaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "WorkSubmitted"
  ): TypedContractEvent<
    WorkSubmittedEvent.InputTuple,
    WorkSubmittedEvent.OutputTuple,
    WorkSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "WorkerSelected"
  ): TypedContractEvent<
    WorkerSelectedEvent.InputTuple,
    WorkerSelectedEvent.OutputTuple,
    WorkerSelectedEvent.OutputObject
  >;

  filters: {
    "ApplicationSubmitted(uint256,address)": TypedContractEvent<
      ApplicationSubmittedEvent.InputTuple,
      ApplicationSubmittedEvent.OutputTuple,
      ApplicationSubmittedEvent.OutputObject
    >;
    ApplicationSubmitted: TypedContractEvent<
      ApplicationSubmittedEvent.InputTuple,
      ApplicationSubmittedEvent.OutputTuple,
      ApplicationSubmittedEvent.OutputObject
    >;

    "DisputeRaised(uint256,uint256)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(uint256,bool)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "EscrowCreated(uint256,address)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "JobCancelled(uint256)": TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;
    JobCancelled: TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;

    "JobPosted(uint256,address,string,uint256,uint256)": TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;
    JobPosted: TypedContractEvent<
      JobPostedEvent.InputTuple,
      JobPostedEvent.OutputTuple,
      JobPostedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentReleased(uint256,address,uint256)": TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
    PaymentReleased: TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;

    "WorkSubmitted(uint256,string)": TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;
    WorkSubmitted: TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;

    "WorkerSelected(uint256,address)": TypedContractEvent<
      WorkerSelectedEvent.InputTuple,
      WorkerSelectedEvent.OutputTuple,
      WorkerSelectedEvent.OutputObject
    >;
    WorkerSelected: TypedContractEvent<
      WorkerSelectedEvent.InputTuple,
      WorkerSelectedEvent.OutputTuple,
      WorkerSelectedEvent.OutputObject
    >;
  };
}
