/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Negotiation {
  export type OfferStruct = {
    offerId: BigNumberish;
    jobId: BigNumberish;
    client: AddressLike;
    worker: AddressLike;
    title: string;
    termsHash: string;
    budget: BigNumberish;
    timeline: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
  };

  export type OfferStructOutput = [
    offerId: bigint,
    jobId: bigint,
    client: string,
    worker: string,
    title: string,
    termsHash: string,
    budget: bigint,
    timeline: bigint,
    status: bigint,
    createdAt: bigint
  ] & {
    offerId: bigint;
    jobId: bigint;
    client: string;
    worker: string;
    title: string;
    termsHash: string;
    budget: bigint;
    timeline: bigint;
    status: bigint;
    createdAt: bigint;
  };
}

export interface NegotiationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOffer"
      | "counterOffer"
      | "getOffer"
      | "makeOffer"
      | "offerCounter"
      | "offers"
      | "rejectOffer"
      | "userOffers"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OfferCountered"
      | "OfferMade"
      | "OfferStatusChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "counterOffer",
    values: [BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "makeOffer",
    values: [
      AddressLike,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "offerCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "offers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userOffers",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "counterOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOffer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "makeOffer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "offerCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "offers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rejectOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userOffers", data: BytesLike): Result;
}

export namespace OfferCounteredEvent {
  export type InputTuple = [
    originalOfferId: BigNumberish,
    newOfferId: BigNumberish
  ];
  export type OutputTuple = [originalOfferId: bigint, newOfferId: bigint];
  export interface OutputObject {
    originalOfferId: bigint;
    newOfferId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferMadeEvent {
  export type InputTuple = [
    offerId: BigNumberish,
    client: AddressLike,
    worker: AddressLike,
    budget: BigNumberish
  ];
  export type OutputTuple = [
    offerId: bigint,
    client: string,
    worker: string,
    budget: bigint
  ];
  export interface OutputObject {
    offerId: bigint;
    client: string;
    worker: string;
    budget: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferStatusChangedEvent {
  export type InputTuple = [offerId: BigNumberish, status: BigNumberish];
  export type OutputTuple = [offerId: bigint, status: bigint];
  export interface OutputObject {
    offerId: bigint;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Negotiation extends BaseContract {
  connect(runner?: ContractRunner | null): Negotiation;
  waitForDeployment(): Promise<this>;

  interface: NegotiationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOffer: TypedContractMethod<
    [_offerId: BigNumberish],
    [void],
    "nonpayable"
  >;

  counterOffer: TypedContractMethod<
    [
      _originalOfferId: BigNumberish,
      _newBudget: BigNumberish,
      _newTimeline: BigNumberish,
      _newTermsHash: string
    ],
    [bigint],
    "nonpayable"
  >;

  getOffer: TypedContractMethod<
    [_offerId: BigNumberish],
    [Negotiation.OfferStructOutput],
    "view"
  >;

  makeOffer: TypedContractMethod<
    [
      _worker: AddressLike,
      _jobId: BigNumberish,
      _title: string,
      _termsHash: string,
      _budget: BigNumberish,
      _timeline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  offerCounter: TypedContractMethod<[], [bigint], "view">;

  offers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        offerId: bigint;
        jobId: bigint;
        client: string;
        worker: string;
        title: string;
        termsHash: string;
        budget: bigint;
        timeline: bigint;
        status: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  rejectOffer: TypedContractMethod<
    [_offerId: BigNumberish],
    [void],
    "nonpayable"
  >;

  userOffers: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOffer"
  ): TypedContractMethod<[_offerId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "counterOffer"
  ): TypedContractMethod<
    [
      _originalOfferId: BigNumberish,
      _newBudget: BigNumberish,
      _newTimeline: BigNumberish,
      _newTermsHash: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getOffer"
  ): TypedContractMethod<
    [_offerId: BigNumberish],
    [Negotiation.OfferStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "makeOffer"
  ): TypedContractMethod<
    [
      _worker: AddressLike,
      _jobId: BigNumberish,
      _title: string,
      _termsHash: string,
      _budget: BigNumberish,
      _timeline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "offerCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "offers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        offerId: bigint;
        jobId: bigint;
        client: string;
        worker: string;
        title: string;
        termsHash: string;
        budget: bigint;
        timeline: bigint;
        status: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rejectOffer"
  ): TypedContractMethod<[_offerId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userOffers"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "OfferCountered"
  ): TypedContractEvent<
    OfferCounteredEvent.InputTuple,
    OfferCounteredEvent.OutputTuple,
    OfferCounteredEvent.OutputObject
  >;
  getEvent(
    key: "OfferMade"
  ): TypedContractEvent<
    OfferMadeEvent.InputTuple,
    OfferMadeEvent.OutputTuple,
    OfferMadeEvent.OutputObject
  >;
  getEvent(
    key: "OfferStatusChanged"
  ): TypedContractEvent<
    OfferStatusChangedEvent.InputTuple,
    OfferStatusChangedEvent.OutputTuple,
    OfferStatusChangedEvent.OutputObject
  >;

  filters: {
    "OfferCountered(uint256,uint256)": TypedContractEvent<
      OfferCounteredEvent.InputTuple,
      OfferCounteredEvent.OutputTuple,
      OfferCounteredEvent.OutputObject
    >;
    OfferCountered: TypedContractEvent<
      OfferCounteredEvent.InputTuple,
      OfferCounteredEvent.OutputTuple,
      OfferCounteredEvent.OutputObject
    >;

    "OfferMade(uint256,address,address,uint256)": TypedContractEvent<
      OfferMadeEvent.InputTuple,
      OfferMadeEvent.OutputTuple,
      OfferMadeEvent.OutputObject
    >;
    OfferMade: TypedContractEvent<
      OfferMadeEvent.InputTuple,
      OfferMadeEvent.OutputTuple,
      OfferMadeEvent.OutputObject
    >;

    "OfferStatusChanged(uint256,uint8)": TypedContractEvent<
      OfferStatusChangedEvent.InputTuple,
      OfferStatusChangedEvent.OutputTuple,
      OfferStatusChangedEvent.OutputObject
    >;
    OfferStatusChanged: TypedContractEvent<
      OfferStatusChangedEvent.InputTuple,
      OfferStatusChangedEvent.OutputTuple,
      OfferStatusChangedEvent.OutputObject
    >;
  };
}
