/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ReputationSystem {
  export type JobRecordStruct = {
    worker: AddressLike;
    client: AddressLike;
    completed: boolean;
    workerRated: boolean;
    clientRated: boolean;
  };

  export type JobRecordStructOutput = [
    worker: string,
    client: string,
    completed: boolean,
    workerRated: boolean,
    clientRated: boolean
  ] & {
    worker: string;
    client: string;
    completed: boolean;
    workerRated: boolean;
    clientRated: boolean;
  };

  export type ReputationStruct = {
    completedJobs: BigNumberish;
    disputeWins: BigNumberish;
    disputeLosses: BigNumberish;
    totalVolume: BigNumberish;
    ratingsSum: BigNumberish;
    ratingCount: BigNumberish;
  };

  export type ReputationStructOutput = [
    completedJobs: bigint,
    disputeWins: bigint,
    disputeLosses: bigint,
    totalVolume: bigint,
    ratingsSum: bigint,
    ratingCount: bigint
  ] & {
    completedJobs: bigint;
    disputeWins: bigint;
    disputeLosses: bigint;
    totalVolume: bigint;
    ratingsSum: bigint;
    ratingCount: bigint;
  };
}

export interface ReputationSystemInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "areBothRatingsComplete"
      | "authorizedCallers"
      | "disputeResolved"
      | "getAverageRatingScaled"
      | "getJobRecord"
      | "getReputation"
      | "isDisputeRecorded"
      | "isJobRecorded"
      | "jobs"
      | "marketplace"
      | "owner"
      | "recordDisputeResult"
      | "recordJobCompletion"
      | "renounceOwnership"
      | "reputations"
      | "setAuthorizedCaller"
      | "setMarketplace"
      | "transferOwnership"
      | "updateRating"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeResultRecorded"
      | "JobCompleted"
      | "OwnershipTransferred"
      | "RatingReceived"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "areBothRatingsComplete",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedCallers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeResolved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAverageRatingScaled",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getJobRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDisputeRecorded",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isJobRecorded",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "marketplace",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordDisputeResult",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordJobCompletion",
    values: [BigNumberish, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedCaller",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketplace",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRating",
    values: [BigNumberish, AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "areBothRatingsComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeResolved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAverageRatingScaled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getJobRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDisputeRecorded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isJobRecorded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordDisputeResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordJobCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRating",
    data: BytesLike
  ): Result;
}

export namespace DisputeResultRecordedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    winner: AddressLike,
    loser: AddressLike
  ];
  export type OutputTuple = [disputeId: bigint, winner: string, loser: string];
  export interface OutputObject {
    disputeId: bigint;
    winner: string;
    loser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCompletedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    worker: AddressLike,
    client: AddressLike,
    volume: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    worker: string,
    client: string,
    volume: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    worker: string;
    client: string;
    volume: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatingReceivedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    user: AddressLike,
    rater: AddressLike,
    rating: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    user: string,
    rater: string,
    rating: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    user: string;
    rater: string;
    rating: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationSystem extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationSystem;
  waitForDeployment(): Promise<this>;

  interface: ReputationSystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  areBothRatingsComplete: TypedContractMethod<
    [_jobId: BigNumberish],
    [boolean],
    "view"
  >;

  authorizedCallers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  disputeResolved: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getAverageRatingScaled: TypedContractMethod<
    [_user: AddressLike],
    [bigint],
    "view"
  >;

  getJobRecord: TypedContractMethod<
    [_jobId: BigNumberish],
    [ReputationSystem.JobRecordStructOutput],
    "view"
  >;

  getReputation: TypedContractMethod<
    [_user: AddressLike],
    [ReputationSystem.ReputationStructOutput],
    "view"
  >;

  isDisputeRecorded: TypedContractMethod<
    [_disputeId: BigNumberish],
    [boolean],
    "view"
  >;

  isJobRecorded: TypedContractMethod<[_jobId: BigNumberish], [boolean], "view">;

  jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, boolean, boolean] & {
        worker: string;
        client: string;
        completed: boolean;
        workerRated: boolean;
        clientRated: boolean;
      }
    ],
    "view"
  >;

  marketplace: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordDisputeResult: TypedContractMethod<
    [_disputeId: BigNumberish, _winner: AddressLike, _loser: AddressLike],
    [void],
    "nonpayable"
  >;

  recordJobCompletion: TypedContractMethod<
    [
      _jobId: BigNumberish,
      _worker: AddressLike,
      _client: AddressLike,
      _amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputations: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        completedJobs: bigint;
        disputeWins: bigint;
        disputeLosses: bigint;
        totalVolume: bigint;
        ratingsSum: bigint;
        ratingCount: bigint;
      }
    ],
    "view"
  >;

  setAuthorizedCaller: TypedContractMethod<
    [_caller: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  setMarketplace: TypedContractMethod<
    [_marketplace: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateRating: TypedContractMethod<
    [
      _jobId: BigNumberish,
      _user: AddressLike,
      _rater: AddressLike,
      _rating: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "areBothRatingsComplete"
  ): TypedContractMethod<[_jobId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "authorizedCallers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "disputeResolved"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAverageRatingScaled"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getJobRecord"
  ): TypedContractMethod<
    [_jobId: BigNumberish],
    [ReputationSystem.JobRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<
    [_user: AddressLike],
    [ReputationSystem.ReputationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isDisputeRecorded"
  ): TypedContractMethod<[_disputeId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isJobRecorded"
  ): TypedContractMethod<[_jobId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, boolean, boolean] & {
        worker: string;
        client: string;
        completed: boolean;
        workerRated: boolean;
        clientRated: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketplace"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordDisputeResult"
  ): TypedContractMethod<
    [_disputeId: BigNumberish, _winner: AddressLike, _loser: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordJobCompletion"
  ): TypedContractMethod<
    [
      _jobId: BigNumberish,
      _worker: AddressLike,
      _client: AddressLike,
      _amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputations"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        completedJobs: bigint;
        disputeWins: bigint;
        disputeLosses: bigint;
        totalVolume: bigint;
        ratingsSum: bigint;
        ratingCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAuthorizedCaller"
  ): TypedContractMethod<
    [_caller: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMarketplace"
  ): TypedContractMethod<[_marketplace: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRating"
  ): TypedContractMethod<
    [
      _jobId: BigNumberish,
      _user: AddressLike,
      _rater: AddressLike,
      _rating: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DisputeResultRecorded"
  ): TypedContractEvent<
    DisputeResultRecordedEvent.InputTuple,
    DisputeResultRecordedEvent.OutputTuple,
    DisputeResultRecordedEvent.OutputObject
  >;
  getEvent(
    key: "JobCompleted"
  ): TypedContractEvent<
    JobCompletedEvent.InputTuple,
    JobCompletedEvent.OutputTuple,
    JobCompletedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RatingReceived"
  ): TypedContractEvent<
    RatingReceivedEvent.InputTuple,
    RatingReceivedEvent.OutputTuple,
    RatingReceivedEvent.OutputObject
  >;

  filters: {
    "DisputeResultRecorded(uint256,address,address)": TypedContractEvent<
      DisputeResultRecordedEvent.InputTuple,
      DisputeResultRecordedEvent.OutputTuple,
      DisputeResultRecordedEvent.OutputObject
    >;
    DisputeResultRecorded: TypedContractEvent<
      DisputeResultRecordedEvent.InputTuple,
      DisputeResultRecordedEvent.OutputTuple,
      DisputeResultRecordedEvent.OutputObject
    >;

    "JobCompleted(uint256,address,address,uint256)": TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;
    JobCompleted: TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RatingReceived(uint256,address,address,uint8)": TypedContractEvent<
      RatingReceivedEvent.InputTuple,
      RatingReceivedEvent.OutputTuple,
      RatingReceivedEvent.OutputObject
    >;
    RatingReceived: TypedContractEvent<
      RatingReceivedEvent.InputTuple,
      RatingReceivedEvent.OutputTuple,
      RatingReceivedEvent.OutputObject
    >;
  };
}
