/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace WorkerRegistry {
  export type ProfileStruct = {
    ipfsHash: BytesLike;
    hourlyRate: BigNumberish;
    registeredAt: BigNumberish;
    isActive: boolean;
  };

  export type ProfileStructOutput = [
    ipfsHash: string,
    hourlyRate: bigint,
    registeredAt: bigint,
    isActive: boolean
  ] & {
    ipfsHash: string;
    hourlyRate: bigint;
    registeredAt: bigint;
    isActive: boolean;
  };
}

export interface WorkerRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DOMAIN_SEPARATOR"
      | "MIN_HOURLY_RATE"
      | "REGISTER_TYPEHASH"
      | "acceptSignerRole"
      | "activeWorkerCount"
      | "admin"
      | "allWorkers"
      | "deregisterProfile"
      | "getDomainSeparator"
      | "getWorker"
      | "getWorkerCount"
      | "getWorkerInfo"
      | "getWorkersPaginated"
      | "isActiveWorker"
      | "nonces"
      | "pendingSigner"
      | "profiles"
      | "proposeSignerUpdate"
      | "registerProfile"
      | "registrationSigner"
      | "transferAdmin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminTransferred"
      | "ProfileDeregistered"
      | "ProfileRegistered"
      | "ProfileUpdated"
      | "SignerUpdateProposed"
      | "SignerUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_HOURLY_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REGISTER_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptSignerRole",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeWorkerCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allWorkers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deregisterProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDomainSeparator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWorker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkerInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkersPaginated",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveWorker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "pendingSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "profiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeSignerUpdate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProfile",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registrationSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_HOURLY_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REGISTER_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptSignerRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeWorkerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allWorkers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deregisterProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDomainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWorker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWorkerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkerInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkersPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isActiveWorker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "profiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeSignerUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registrationSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
}

export namespace AdminTransferredEvent {
  export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [oldAdmin: string, newAdmin: string];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileDeregisteredEvent {
  export type InputTuple = [worker: AddressLike];
  export type OutputTuple = [worker: string];
  export interface OutputObject {
    worker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileRegisteredEvent {
  export type InputTuple = [
    worker: AddressLike,
    ipfsHash: BytesLike,
    hourlyRate: BigNumberish
  ];
  export type OutputTuple = [
    worker: string,
    ipfsHash: string,
    hourlyRate: bigint
  ];
  export interface OutputObject {
    worker: string;
    ipfsHash: string;
    hourlyRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileUpdatedEvent {
  export type InputTuple = [
    worker: AddressLike,
    ipfsHash: BytesLike,
    hourlyRate: BigNumberish
  ];
  export type OutputTuple = [
    worker: string,
    ipfsHash: string,
    hourlyRate: bigint
  ];
  export interface OutputObject {
    worker: string;
    ipfsHash: string;
    hourlyRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerUpdateProposedEvent {
  export type InputTuple = [
    currentSigner: AddressLike,
    proposedSigner: AddressLike
  ];
  export type OutputTuple = [currentSigner: string, proposedSigner: string];
  export interface OutputObject {
    currentSigner: string;
    proposedSigner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerUpdatedEvent {
  export type InputTuple = [oldSigner: AddressLike, newSigner: AddressLike];
  export type OutputTuple = [oldSigner: string, newSigner: string];
  export interface OutputObject {
    oldSigner: string;
    newSigner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WorkerRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): WorkerRegistry;
  waitForDeployment(): Promise<this>;

  interface: WorkerRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DOMAIN_SEPARATOR: TypedContractMethod<[], [string], "view">;

  MIN_HOURLY_RATE: TypedContractMethod<[], [bigint], "view">;

  REGISTER_TYPEHASH: TypedContractMethod<[], [string], "view">;

  acceptSignerRole: TypedContractMethod<[], [void], "nonpayable">;

  activeWorkerCount: TypedContractMethod<[], [bigint], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  allWorkers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  deregisterProfile: TypedContractMethod<[], [void], "nonpayable">;

  getDomainSeparator: TypedContractMethod<[], [string], "view">;

  getWorker: TypedContractMethod<
    [_worker: AddressLike],
    [WorkerRegistry.ProfileStructOutput],
    "view"
  >;

  getWorkerCount: TypedContractMethod<[], [bigint], "view">;

  getWorkerInfo: TypedContractMethod<
    [_worker: AddressLike],
    [
      [string, bigint, boolean, bigint] & {
        ipfsHash: string;
        hourlyRate: bigint;
        isActive: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  getWorkersPaginated: TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [string[]],
    "view"
  >;

  isActiveWorker: TypedContractMethod<
    [_worker: AddressLike],
    [boolean],
    "view"
  >;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  pendingSigner: TypedContractMethod<[], [string], "view">;

  profiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        ipfsHash: string;
        hourlyRate: bigint;
        registeredAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  proposeSignerUpdate: TypedContractMethod<
    [_newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  registerProfile: TypedContractMethod<
    [
      _ipfsHash: BytesLike,
      _hourlyRate: BigNumberish,
      _deadline: BigNumberish,
      _signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  registrationSigner: TypedContractMethod<[], [string], "view">;

  transferAdmin: TypedContractMethod<
    [_newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DOMAIN_SEPARATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MIN_HOURLY_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REGISTER_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptSignerRole"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "activeWorkerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allWorkers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "deregisterProfile"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDomainSeparator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getWorker"
  ): TypedContractMethod<
    [_worker: AddressLike],
    [WorkerRegistry.ProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWorkerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWorkerInfo"
  ): TypedContractMethod<
    [_worker: AddressLike],
    [
      [string, bigint, boolean, bigint] & {
        ipfsHash: string;
        hourlyRate: bigint;
        isActive: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWorkersPaginated"
  ): TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActiveWorker"
  ): TypedContractMethod<[_worker: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "profiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        ipfsHash: string;
        hourlyRate: bigint;
        registeredAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposeSignerUpdate"
  ): TypedContractMethod<[_newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerProfile"
  ): TypedContractMethod<
    [
      _ipfsHash: BytesLike,
      _hourlyRate: BigNumberish,
      _deadline: BigNumberish,
      _signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registrationSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AdminTransferred"
  ): TypedContractEvent<
    AdminTransferredEvent.InputTuple,
    AdminTransferredEvent.OutputTuple,
    AdminTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProfileDeregistered"
  ): TypedContractEvent<
    ProfileDeregisteredEvent.InputTuple,
    ProfileDeregisteredEvent.OutputTuple,
    ProfileDeregisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProfileRegistered"
  ): TypedContractEvent<
    ProfileRegisteredEvent.InputTuple,
    ProfileRegisteredEvent.OutputTuple,
    ProfileRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProfileUpdated"
  ): TypedContractEvent<
    ProfileUpdatedEvent.InputTuple,
    ProfileUpdatedEvent.OutputTuple,
    ProfileUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SignerUpdateProposed"
  ): TypedContractEvent<
    SignerUpdateProposedEvent.InputTuple,
    SignerUpdateProposedEvent.OutputTuple,
    SignerUpdateProposedEvent.OutputObject
  >;
  getEvent(
    key: "SignerUpdated"
  ): TypedContractEvent<
    SignerUpdatedEvent.InputTuple,
    SignerUpdatedEvent.OutputTuple,
    SignerUpdatedEvent.OutputObject
  >;

  filters: {
    "AdminTransferred(address,address)": TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;
    AdminTransferred: TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;

    "ProfileDeregistered(address)": TypedContractEvent<
      ProfileDeregisteredEvent.InputTuple,
      ProfileDeregisteredEvent.OutputTuple,
      ProfileDeregisteredEvent.OutputObject
    >;
    ProfileDeregistered: TypedContractEvent<
      ProfileDeregisteredEvent.InputTuple,
      ProfileDeregisteredEvent.OutputTuple,
      ProfileDeregisteredEvent.OutputObject
    >;

    "ProfileRegistered(address,bytes32,uint256)": TypedContractEvent<
      ProfileRegisteredEvent.InputTuple,
      ProfileRegisteredEvent.OutputTuple,
      ProfileRegisteredEvent.OutputObject
    >;
    ProfileRegistered: TypedContractEvent<
      ProfileRegisteredEvent.InputTuple,
      ProfileRegisteredEvent.OutputTuple,
      ProfileRegisteredEvent.OutputObject
    >;

    "ProfileUpdated(address,bytes32,uint256)": TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
    ProfileUpdated: TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;

    "SignerUpdateProposed(address,address)": TypedContractEvent<
      SignerUpdateProposedEvent.InputTuple,
      SignerUpdateProposedEvent.OutputTuple,
      SignerUpdateProposedEvent.OutputObject
    >;
    SignerUpdateProposed: TypedContractEvent<
      SignerUpdateProposedEvent.InputTuple,
      SignerUpdateProposedEvent.OutputTuple,
      SignerUpdateProposedEvent.OutputObject
    >;

    "SignerUpdated(address,address)": TypedContractEvent<
      SignerUpdatedEvent.InputTuple,
      SignerUpdatedEvent.OutputTuple,
      SignerUpdatedEvent.OutputObject
    >;
    SignerUpdated: TypedContractEvent<
      SignerUpdatedEvent.InputTuple,
      SignerUpdatedEvent.OutputTuple,
      SignerUpdatedEvent.OutputObject
    >;
  };
}
