/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ArbitrationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "APPEAL_JUROR_INCREMENT"
      | "APPEAL_PERIOD"
      | "ARBITRATION_FEE"
      | "EVIDENCE_PERIOD"
      | "INITIAL_JUROR_COUNT"
      | "MAX_CATEGORIES"
      | "MAX_JURORS_PER_DISPUTE"
      | "REVEAL_QUORUM_PERCENTAGE"
      | "SLASH_PERCENTAGE"
      | "STAKE_AMOUNT"
      | "STAKE_LOCK_PER_DISPUTE"
      | "USDC_ADDRESS"
      | "addCategory"
      | "addStake"
      | "appealDispute"
      | "categoryCounter"
      | "categoryNames"
      | "claimReward"
      | "claimRewardsBatch"
      | "commitVote"
      | "completeJurorSelection"
      | "createDispute"
      | "disputeCounter"
      | "disputes"
      | "finalizeDispute"
      | "getDisputeResult"
      | "getEvidence"
      | "getEvidenceCount"
      | "getSelectedJurors"
      | "jurors"
      | "marketplace"
      | "randomnessOracle"
      | "retryDisputeRound"
      | "revealVote"
      | "setMarketplace"
      | "setRandomnessOracle"
      | "setTreasury"
      | "stakeAsJuror"
      | "submitEvidence"
      | "treasury"
      | "unstake"
      | "usdc"
      | "validCategories"
      | "withdrawRewards"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CategoryAdded"
      | "DisputeAppealed"
      | "DisputeCreated"
      | "DisputeResolved"
      | "DisputeRetried"
      | "EvidenceSubmitted"
      | "JurorEligibilityRestored"
      | "JurorRewardsWithdrawn"
      | "JurorSelected"
      | "JurorSelectionCompleted"
      | "JurorSlashed"
      | "JurorStakeAdded"
      | "JurorStaked"
      | "JurorUnstaked"
      | "RandomnessRequested"
      | "RewardClaimed"
      | "TreasuryFundsDeposited"
      | "VoteCast"
      | "VoteCommitted"
      | "VoteRevealed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "APPEAL_JUROR_INCREMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "APPEAL_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ARBITRATION_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EVIDENCE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_JUROR_COUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_CATEGORIES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_JURORS_PER_DISPUTE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REVEAL_QUORUM_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SLASH_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STAKE_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STAKE_LOCK_PER_DISPUTE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDC_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "addCategory", values: [string]): string;
  encodeFunctionData(
    functionFragment: "addStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "appealDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "categoryCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "categoryNames",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewardsBatch",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "commitVote",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeJurorSelection",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDispute",
    values: [BigNumberish, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDisputeResult",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidence",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidenceCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSelectedJurors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "jurors", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "marketplace",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "randomnessOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "retryDisputeRound",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revealVote",
    values: [BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketplace",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRandomnessOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeAsJuror",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEvidence",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unstake", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "validCategories",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRewards",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "APPEAL_JUROR_INCREMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "APPEAL_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ARBITRATION_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EVIDENCE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_JUROR_COUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_CATEGORIES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_JURORS_PER_DISPUTE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REVEAL_QUORUM_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SLASH_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STAKE_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STAKE_LOCK_PER_DISPUTE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDC_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "appealDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "categoryCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "categoryNames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewardsBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "commitVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeJurorSelection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDisputeResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidenceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSelectedJurors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jurors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "randomnessOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retryDisputeRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revealVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMarketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRandomnessOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeAsJuror",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validCategories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRewards",
    data: BytesLike
  ): Result;
}

export namespace CategoryAddedEvent {
  export type InputTuple = [categoryId: BigNumberish, name: string];
  export type OutputTuple = [categoryId: bigint, name: string];
  export interface OutputObject {
    categoryId: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeAppealedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    newJurorCount: BigNumberish
  ];
  export type OutputTuple = [disputeId: bigint, newJurorCount: bigint];
  export interface OutputObject {
    disputeId: bigint;
    newJurorCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeCreatedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    jobId: BigNumberish,
    categoryId: BigNumberish
  ];
  export type OutputTuple = [
    disputeId: bigint,
    jobId: bigint,
    categoryId: bigint
  ];
  export interface OutputObject {
    disputeId: bigint;
    jobId: bigint;
    categoryId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    clientWon: boolean,
    majorityVotes: BigNumberish
  ];
  export type OutputTuple = [
    disputeId: bigint,
    clientWon: boolean,
    majorityVotes: bigint
  ];
  export interface OutputObject {
    disputeId: bigint;
    clientWon: boolean;
    majorityVotes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRetriedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    reason: string,
    newJurorCount: BigNumberish
  ];
  export type OutputTuple = [
    disputeId: bigint,
    reason: string,
    newJurorCount: bigint
  ];
  export interface OutputObject {
    disputeId: bigint;
    reason: string;
    newJurorCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceSubmittedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    submitter: AddressLike,
    evidenceHash: string
  ];
  export type OutputTuple = [
    disputeId: bigint,
    submitter: string,
    evidenceHash: string
  ];
  export interface OutputObject {
    disputeId: bigint;
    submitter: string;
    evidenceHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurorEligibilityRestoredEvent {
  export type InputTuple = [juror: AddressLike];
  export type OutputTuple = [juror: string];
  export interface OutputObject {
    juror: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurorRewardsWithdrawnEvent {
  export type InputTuple = [juror: AddressLike, amount: BigNumberish];
  export type OutputTuple = [juror: string, amount: bigint];
  export interface OutputObject {
    juror: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurorSelectedEvent {
  export type InputTuple = [disputeId: BigNumberish, juror: AddressLike];
  export type OutputTuple = [disputeId: bigint, juror: string];
  export interface OutputObject {
    disputeId: bigint;
    juror: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurorSelectionCompletedEvent {
  export type InputTuple = [disputeId: BigNumberish, jurorCount: BigNumberish];
  export type OutputTuple = [disputeId: bigint, jurorCount: bigint];
  export interface OutputObject {
    disputeId: bigint;
    jurorCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurorSlashedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    juror: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    disputeId: bigint,
    juror: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    disputeId: bigint;
    juror: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurorStakeAddedEvent {
  export type InputTuple = [
    juror: AddressLike,
    amount: BigNumberish,
    newTotal: BigNumberish
  ];
  export type OutputTuple = [juror: string, amount: bigint, newTotal: bigint];
  export interface OutputObject {
    juror: string;
    amount: bigint;
    newTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurorStakedEvent {
  export type InputTuple = [
    juror: AddressLike,
    amount: BigNumberish,
    categoryIds: BigNumberish[]
  ];
  export type OutputTuple = [
    juror: string,
    amount: bigint,
    categoryIds: bigint[]
  ];
  export interface OutputObject {
    juror: string;
    amount: bigint;
    categoryIds: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurorUnstakedEvent {
  export type InputTuple = [juror: AddressLike, amount: BigNumberish];
  export type OutputTuple = [juror: string, amount: bigint];
  export interface OutputObject {
    juror: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RandomnessRequestedEvent {
  export type InputTuple = [disputeId: BigNumberish, requestId: BytesLike];
  export type OutputTuple = [disputeId: bigint, requestId: string];
  export interface OutputObject {
    disputeId: bigint;
    requestId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    juror: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [disputeId: bigint, juror: string, amount: bigint];
  export interface OutputObject {
    disputeId: bigint;
    juror: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryFundsDepositedEvent {
  export type InputTuple = [disputeId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [disputeId: bigint, amount: bigint];
  export interface OutputObject {
    disputeId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    juror: AddressLike,
    votedForClient: boolean
  ];
  export type OutputTuple = [
    disputeId: bigint,
    juror: string,
    votedForClient: boolean
  ];
  export interface OutputObject {
    disputeId: bigint;
    juror: string;
    votedForClient: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCommittedEvent {
  export type InputTuple = [disputeId: BigNumberish, juror: AddressLike];
  export type OutputTuple = [disputeId: bigint, juror: string];
  export interface OutputObject {
    disputeId: bigint;
    juror: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteRevealedEvent {
  export type InputTuple = [
    disputeId: BigNumberish,
    juror: AddressLike,
    voteForClient: boolean
  ];
  export type OutputTuple = [
    disputeId: bigint,
    juror: string,
    voteForClient: boolean
  ];
  export interface OutputObject {
    disputeId: bigint;
    juror: string;
    voteForClient: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Arbitration extends BaseContract {
  connect(runner?: ContractRunner | null): Arbitration;
  waitForDeployment(): Promise<this>;

  interface: ArbitrationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  APPEAL_JUROR_INCREMENT: TypedContractMethod<[], [bigint], "view">;

  APPEAL_PERIOD: TypedContractMethod<[], [bigint], "view">;

  ARBITRATION_FEE: TypedContractMethod<[], [bigint], "view">;

  EVIDENCE_PERIOD: TypedContractMethod<[], [bigint], "view">;

  INITIAL_JUROR_COUNT: TypedContractMethod<[], [bigint], "view">;

  MAX_CATEGORIES: TypedContractMethod<[], [bigint], "view">;

  MAX_JURORS_PER_DISPUTE: TypedContractMethod<[], [bigint], "view">;

  REVEAL_QUORUM_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  SLASH_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  STAKE_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  STAKE_LOCK_PER_DISPUTE: TypedContractMethod<[], [bigint], "view">;

  USDC_ADDRESS: TypedContractMethod<[], [string], "view">;

  addCategory: TypedContractMethod<[_name: string], [void], "nonpayable">;

  addStake: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  appealDispute: TypedContractMethod<
    [_disputeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  categoryCounter: TypedContractMethod<[], [bigint], "view">;

  categoryNames: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  claimReward: TypedContractMethod<
    [_disputeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRewardsBatch: TypedContractMethod<
    [_disputeIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  commitVote: TypedContractMethod<
    [_disputeId: BigNumberish, _commitHash: BytesLike],
    [void],
    "nonpayable"
  >;

  completeJurorSelection: TypedContractMethod<
    [_disputeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createDispute: TypedContractMethod<
    [
      _jobId: BigNumberish,
      _client: AddressLike,
      _worker: AddressLike,
      _categoryId: BigNumberish,
      _amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  disputeCounter: TypedContractMethod<[], [bigint], "view">;

  disputes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean
      ] & {
        disputeId: bigint;
        jobId: bigint;
        client: string;
        worker: string;
        categoryId: bigint;
        amount: bigint;
        isActive: boolean;
        isResolved: boolean;
        votesForClient: bigint;
        votesForWorker: bigint;
        jurorCount: bigint;
        appealCount: bigint;
        revealCount: bigint;
        arbitrationFeePaid: bigint;
        totalSlashed: bigint;
        winnerCount: bigint;
        clientWon: boolean;
        rewardPerWinner: bigint;
        createdAt: bigint;
        evidencePeriodEnd: bigint;
        commitPeriodEnd: bigint;
        revealPeriodEnd: bigint;
        appealPeriodEnd: bigint;
        randomnessRequestId: string;
        jurorSelectionPending: boolean;
      }
    ],
    "view"
  >;

  finalizeDispute: TypedContractMethod<
    [_disputeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getDisputeResult: TypedContractMethod<
    [_disputeId: BigNumberish],
    [[boolean, boolean] & { isResolved: boolean; clientWon: boolean }],
    "view"
  >;

  getEvidence: TypedContractMethod<
    [_disputeId: BigNumberish, _index: BigNumberish],
    [string],
    "view"
  >;

  getEvidenceCount: TypedContractMethod<
    [_disputeId: BigNumberish],
    [bigint],
    "view"
  >;

  getSelectedJurors: TypedContractMethod<
    [_disputeId: BigNumberish],
    [string[]],
    "view"
  >;

  jurors: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint, bigint, bigint] & {
        isStaked: boolean;
        isEligible: boolean;
        stakedAmount: bigint;
        lockedStake: bigint;
        casesVoted: bigint;
        correctVotes: bigint;
        activeDisputeCount: bigint;
      }
    ],
    "view"
  >;

  marketplace: TypedContractMethod<[], [string], "view">;

  randomnessOracle: TypedContractMethod<[], [string], "view">;

  retryDisputeRound: TypedContractMethod<
    [_disputeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  revealVote: TypedContractMethod<
    [_disputeId: BigNumberish, _voteForClient: boolean, _salt: string],
    [void],
    "nonpayable"
  >;

  setMarketplace: TypedContractMethod<
    [_marketplace: AddressLike],
    [void],
    "nonpayable"
  >;

  setRandomnessOracle: TypedContractMethod<
    [_oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  stakeAsJuror: TypedContractMethod<
    [_categoryIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  submitEvidence: TypedContractMethod<
    [_disputeId: BigNumberish, _evidenceHash: string],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unstake: TypedContractMethod<[], [void], "nonpayable">;

  usdc: TypedContractMethod<[], [string], "view">;

  validCategories: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  withdrawRewards: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "APPEAL_JUROR_INCREMENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "APPEAL_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ARBITRATION_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EVIDENCE_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_JUROR_COUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_CATEGORIES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_JURORS_PER_DISPUTE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REVEAL_QUORUM_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLASH_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STAKE_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STAKE_LOCK_PER_DISPUTE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addCategory"
  ): TypedContractMethod<[_name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addStake"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "appealDispute"
  ): TypedContractMethod<[_disputeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "categoryCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "categoryNames"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[_disputeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRewardsBatch"
  ): TypedContractMethod<[_disputeIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "commitVote"
  ): TypedContractMethod<
    [_disputeId: BigNumberish, _commitHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "completeJurorSelection"
  ): TypedContractMethod<[_disputeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createDispute"
  ): TypedContractMethod<
    [
      _jobId: BigNumberish,
      _client: AddressLike,
      _worker: AddressLike,
      _categoryId: BigNumberish,
      _amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "disputes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean
      ] & {
        disputeId: bigint;
        jobId: bigint;
        client: string;
        worker: string;
        categoryId: bigint;
        amount: bigint;
        isActive: boolean;
        isResolved: boolean;
        votesForClient: bigint;
        votesForWorker: bigint;
        jurorCount: bigint;
        appealCount: bigint;
        revealCount: bigint;
        arbitrationFeePaid: bigint;
        totalSlashed: bigint;
        winnerCount: bigint;
        clientWon: boolean;
        rewardPerWinner: bigint;
        createdAt: bigint;
        evidencePeriodEnd: bigint;
        commitPeriodEnd: bigint;
        revealPeriodEnd: bigint;
        appealPeriodEnd: bigint;
        randomnessRequestId: string;
        jurorSelectionPending: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "finalizeDispute"
  ): TypedContractMethod<[_disputeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDisputeResult"
  ): TypedContractMethod<
    [_disputeId: BigNumberish],
    [[boolean, boolean] & { isResolved: boolean; clientWon: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvidence"
  ): TypedContractMethod<
    [_disputeId: BigNumberish, _index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvidenceCount"
  ): TypedContractMethod<[_disputeId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSelectedJurors"
  ): TypedContractMethod<[_disputeId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "jurors"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint, bigint, bigint] & {
        isStaked: boolean;
        isEligible: boolean;
        stakedAmount: bigint;
        lockedStake: bigint;
        casesVoted: bigint;
        correctVotes: bigint;
        activeDisputeCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketplace"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "randomnessOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "retryDisputeRound"
  ): TypedContractMethod<[_disputeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revealVote"
  ): TypedContractMethod<
    [_disputeId: BigNumberish, _voteForClient: boolean, _salt: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMarketplace"
  ): TypedContractMethod<[_marketplace: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRandomnessOracle"
  ): TypedContractMethod<[_oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeAsJuror"
  ): TypedContractMethod<[_categoryIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitEvidence"
  ): TypedContractMethod<
    [_disputeId: BigNumberish, _evidenceHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "validCategories"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdrawRewards"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "CategoryAdded"
  ): TypedContractEvent<
    CategoryAddedEvent.InputTuple,
    CategoryAddedEvent.OutputTuple,
    CategoryAddedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeAppealed"
  ): TypedContractEvent<
    DisputeAppealedEvent.InputTuple,
    DisputeAppealedEvent.OutputTuple,
    DisputeAppealedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeCreated"
  ): TypedContractEvent<
    DisputeCreatedEvent.InputTuple,
    DisputeCreatedEvent.OutputTuple,
    DisputeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRetried"
  ): TypedContractEvent<
    DisputeRetriedEvent.InputTuple,
    DisputeRetriedEvent.OutputTuple,
    DisputeRetriedEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceSubmitted"
  ): TypedContractEvent<
    EvidenceSubmittedEvent.InputTuple,
    EvidenceSubmittedEvent.OutputTuple,
    EvidenceSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "JurorEligibilityRestored"
  ): TypedContractEvent<
    JurorEligibilityRestoredEvent.InputTuple,
    JurorEligibilityRestoredEvent.OutputTuple,
    JurorEligibilityRestoredEvent.OutputObject
  >;
  getEvent(
    key: "JurorRewardsWithdrawn"
  ): TypedContractEvent<
    JurorRewardsWithdrawnEvent.InputTuple,
    JurorRewardsWithdrawnEvent.OutputTuple,
    JurorRewardsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "JurorSelected"
  ): TypedContractEvent<
    JurorSelectedEvent.InputTuple,
    JurorSelectedEvent.OutputTuple,
    JurorSelectedEvent.OutputObject
  >;
  getEvent(
    key: "JurorSelectionCompleted"
  ): TypedContractEvent<
    JurorSelectionCompletedEvent.InputTuple,
    JurorSelectionCompletedEvent.OutputTuple,
    JurorSelectionCompletedEvent.OutputObject
  >;
  getEvent(
    key: "JurorSlashed"
  ): TypedContractEvent<
    JurorSlashedEvent.InputTuple,
    JurorSlashedEvent.OutputTuple,
    JurorSlashedEvent.OutputObject
  >;
  getEvent(
    key: "JurorStakeAdded"
  ): TypedContractEvent<
    JurorStakeAddedEvent.InputTuple,
    JurorStakeAddedEvent.OutputTuple,
    JurorStakeAddedEvent.OutputObject
  >;
  getEvent(
    key: "JurorStaked"
  ): TypedContractEvent<
    JurorStakedEvent.InputTuple,
    JurorStakedEvent.OutputTuple,
    JurorStakedEvent.OutputObject
  >;
  getEvent(
    key: "JurorUnstaked"
  ): TypedContractEvent<
    JurorUnstakedEvent.InputTuple,
    JurorUnstakedEvent.OutputTuple,
    JurorUnstakedEvent.OutputObject
  >;
  getEvent(
    key: "RandomnessRequested"
  ): TypedContractEvent<
    RandomnessRequestedEvent.InputTuple,
    RandomnessRequestedEvent.OutputTuple,
    RandomnessRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryFundsDeposited"
  ): TypedContractEvent<
    TreasuryFundsDepositedEvent.InputTuple,
    TreasuryFundsDepositedEvent.OutputTuple,
    TreasuryFundsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;
  getEvent(
    key: "VoteCommitted"
  ): TypedContractEvent<
    VoteCommittedEvent.InputTuple,
    VoteCommittedEvent.OutputTuple,
    VoteCommittedEvent.OutputObject
  >;
  getEvent(
    key: "VoteRevealed"
  ): TypedContractEvent<
    VoteRevealedEvent.InputTuple,
    VoteRevealedEvent.OutputTuple,
    VoteRevealedEvent.OutputObject
  >;

  filters: {
    "CategoryAdded(uint256,string)": TypedContractEvent<
      CategoryAddedEvent.InputTuple,
      CategoryAddedEvent.OutputTuple,
      CategoryAddedEvent.OutputObject
    >;
    CategoryAdded: TypedContractEvent<
      CategoryAddedEvent.InputTuple,
      CategoryAddedEvent.OutputTuple,
      CategoryAddedEvent.OutputObject
    >;

    "DisputeAppealed(uint256,uint256)": TypedContractEvent<
      DisputeAppealedEvent.InputTuple,
      DisputeAppealedEvent.OutputTuple,
      DisputeAppealedEvent.OutputObject
    >;
    DisputeAppealed: TypedContractEvent<
      DisputeAppealedEvent.InputTuple,
      DisputeAppealedEvent.OutputTuple,
      DisputeAppealedEvent.OutputObject
    >;

    "DisputeCreated(uint256,uint256,uint256)": TypedContractEvent<
      DisputeCreatedEvent.InputTuple,
      DisputeCreatedEvent.OutputTuple,
      DisputeCreatedEvent.OutputObject
    >;
    DisputeCreated: TypedContractEvent<
      DisputeCreatedEvent.InputTuple,
      DisputeCreatedEvent.OutputTuple,
      DisputeCreatedEvent.OutputObject
    >;

    "DisputeResolved(uint256,bool,uint256)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "DisputeRetried(uint256,string,uint256)": TypedContractEvent<
      DisputeRetriedEvent.InputTuple,
      DisputeRetriedEvent.OutputTuple,
      DisputeRetriedEvent.OutputObject
    >;
    DisputeRetried: TypedContractEvent<
      DisputeRetriedEvent.InputTuple,
      DisputeRetriedEvent.OutputTuple,
      DisputeRetriedEvent.OutputObject
    >;

    "EvidenceSubmitted(uint256,address,string)": TypedContractEvent<
      EvidenceSubmittedEvent.InputTuple,
      EvidenceSubmittedEvent.OutputTuple,
      EvidenceSubmittedEvent.OutputObject
    >;
    EvidenceSubmitted: TypedContractEvent<
      EvidenceSubmittedEvent.InputTuple,
      EvidenceSubmittedEvent.OutputTuple,
      EvidenceSubmittedEvent.OutputObject
    >;

    "JurorEligibilityRestored(address)": TypedContractEvent<
      JurorEligibilityRestoredEvent.InputTuple,
      JurorEligibilityRestoredEvent.OutputTuple,
      JurorEligibilityRestoredEvent.OutputObject
    >;
    JurorEligibilityRestored: TypedContractEvent<
      JurorEligibilityRestoredEvent.InputTuple,
      JurorEligibilityRestoredEvent.OutputTuple,
      JurorEligibilityRestoredEvent.OutputObject
    >;

    "JurorRewardsWithdrawn(address,uint256)": TypedContractEvent<
      JurorRewardsWithdrawnEvent.InputTuple,
      JurorRewardsWithdrawnEvent.OutputTuple,
      JurorRewardsWithdrawnEvent.OutputObject
    >;
    JurorRewardsWithdrawn: TypedContractEvent<
      JurorRewardsWithdrawnEvent.InputTuple,
      JurorRewardsWithdrawnEvent.OutputTuple,
      JurorRewardsWithdrawnEvent.OutputObject
    >;

    "JurorSelected(uint256,address)": TypedContractEvent<
      JurorSelectedEvent.InputTuple,
      JurorSelectedEvent.OutputTuple,
      JurorSelectedEvent.OutputObject
    >;
    JurorSelected: TypedContractEvent<
      JurorSelectedEvent.InputTuple,
      JurorSelectedEvent.OutputTuple,
      JurorSelectedEvent.OutputObject
    >;

    "JurorSelectionCompleted(uint256,uint256)": TypedContractEvent<
      JurorSelectionCompletedEvent.InputTuple,
      JurorSelectionCompletedEvent.OutputTuple,
      JurorSelectionCompletedEvent.OutputObject
    >;
    JurorSelectionCompleted: TypedContractEvent<
      JurorSelectionCompletedEvent.InputTuple,
      JurorSelectionCompletedEvent.OutputTuple,
      JurorSelectionCompletedEvent.OutputObject
    >;

    "JurorSlashed(uint256,address,uint256,string)": TypedContractEvent<
      JurorSlashedEvent.InputTuple,
      JurorSlashedEvent.OutputTuple,
      JurorSlashedEvent.OutputObject
    >;
    JurorSlashed: TypedContractEvent<
      JurorSlashedEvent.InputTuple,
      JurorSlashedEvent.OutputTuple,
      JurorSlashedEvent.OutputObject
    >;

    "JurorStakeAdded(address,uint256,uint256)": TypedContractEvent<
      JurorStakeAddedEvent.InputTuple,
      JurorStakeAddedEvent.OutputTuple,
      JurorStakeAddedEvent.OutputObject
    >;
    JurorStakeAdded: TypedContractEvent<
      JurorStakeAddedEvent.InputTuple,
      JurorStakeAddedEvent.OutputTuple,
      JurorStakeAddedEvent.OutputObject
    >;

    "JurorStaked(address,uint256,uint256[])": TypedContractEvent<
      JurorStakedEvent.InputTuple,
      JurorStakedEvent.OutputTuple,
      JurorStakedEvent.OutputObject
    >;
    JurorStaked: TypedContractEvent<
      JurorStakedEvent.InputTuple,
      JurorStakedEvent.OutputTuple,
      JurorStakedEvent.OutputObject
    >;

    "JurorUnstaked(address,uint256)": TypedContractEvent<
      JurorUnstakedEvent.InputTuple,
      JurorUnstakedEvent.OutputTuple,
      JurorUnstakedEvent.OutputObject
    >;
    JurorUnstaked: TypedContractEvent<
      JurorUnstakedEvent.InputTuple,
      JurorUnstakedEvent.OutputTuple,
      JurorUnstakedEvent.OutputObject
    >;

    "RandomnessRequested(uint256,bytes32)": TypedContractEvent<
      RandomnessRequestedEvent.InputTuple,
      RandomnessRequestedEvent.OutputTuple,
      RandomnessRequestedEvent.OutputObject
    >;
    RandomnessRequested: TypedContractEvent<
      RandomnessRequestedEvent.InputTuple,
      RandomnessRequestedEvent.OutputTuple,
      RandomnessRequestedEvent.OutputObject
    >;

    "RewardClaimed(uint256,address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "TreasuryFundsDeposited(uint256,uint256)": TypedContractEvent<
      TreasuryFundsDepositedEvent.InputTuple,
      TreasuryFundsDepositedEvent.OutputTuple,
      TreasuryFundsDepositedEvent.OutputObject
    >;
    TreasuryFundsDeposited: TypedContractEvent<
      TreasuryFundsDepositedEvent.InputTuple,
      TreasuryFundsDepositedEvent.OutputTuple,
      TreasuryFundsDepositedEvent.OutputObject
    >;

    "VoteCast(uint256,address,bool)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;

    "VoteCommitted(uint256,address)": TypedContractEvent<
      VoteCommittedEvent.InputTuple,
      VoteCommittedEvent.OutputTuple,
      VoteCommittedEvent.OutputObject
    >;
    VoteCommitted: TypedContractEvent<
      VoteCommittedEvent.InputTuple,
      VoteCommittedEvent.OutputTuple,
      VoteCommittedEvent.OutputObject
    >;

    "VoteRevealed(uint256,address,bool)": TypedContractEvent<
      VoteRevealedEvent.InputTuple,
      VoteRevealedEvent.OutputTuple,
      VoteRevealedEvent.OutputObject
    >;
    VoteRevealed: TypedContractEvent<
      VoteRevealedEvent.InputTuple,
      VoteRevealedEvent.OutputTuple,
      VoteRevealedEvent.OutputObject
    >;
  };
}
