/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRandomnessOracle,
  IRandomnessOracleInterface,
} from "../../../contracts/Arbitration.sol/IRandomnessOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    name: "getRandomNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    name: "isRandomNumberReady",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "requestRandomness",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRandomnessOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomnessOracleInterface {
    return new Interface(_abi) as IRandomnessOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRandomnessOracle {
    return new Contract(address, _abi, runner) as unknown as IRandomnessOracle;
  }
}
