/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWorkerRegistry,
  IWorkerRegistryInterface,
} from "../../../contracts/Arbitration.sol/IWorkerRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_worker",
        type: "address",
      },
    ],
    name: "isActiveWorker",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IWorkerRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IWorkerRegistryInterface {
    return new Interface(_abi) as IWorkerRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWorkerRegistry {
    return new Contract(address, _abi, runner) as unknown as IWorkerRegistry;
  }
}
